[LightDM]
run-directory=/run/lightdm

[Seat:*]
autologin-user=tornuser
autologin-user-timeout=0
autologin-session=openbox
user-session=openbox
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
allow-guest=false
